languageName = "Italiano"
weight = 1
#logo = "logo.png"
title = "bortox.it ðŸ¦… il nido del cuculo  "
copyright = "Contenuto sotto licenza: [ :link: CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0)"

[params]
   rtl = false
   dateFormat = "2/01/06"
   description = "Blog personale"
   displayName = ":it:"
   isoCode = "it"

[author]
  name = "Andrea Bortolotti"
  image = "author.png"
  headline = "I'm only human"
  bio = "Ciao, sono uno studente. [âœ¨ **sostieni** bortox.it âœ¨](https://bortox.it/contribuisci-cs)"
  links = [
     { email = "mailto:bort0x@tuta.io" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/bortox" },
  #   { gitlab = "https://gitlab.com/username" },
     { google = "https://www.google.com/search?q=site:bortox.it" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.uno/@bortox" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/il_bortox" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
   ]
  
